name: Build and Deploy React App to EC2 via Docker

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build and Push Docker Image to Private Registry
      - name: Build & Push Docker image to Private Registry
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: prajapati003/deepak-backand
          tags: ${{ github.sha }}
          registry: invest.virtualintelligence.co.in
          dockerfile: Dockerfile
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Step 3: Test network connectivity to EC2
      - name: Test network connectivity to EC2
        run: |
          echo "Pinging EC2 instance..."
          ping -c 3 ${{ secrets.EC2_HOST }} || true

          echo "Checking SSH port..."
          nc -zv ${{ secrets.EC2_HOST }} 22 || true

      # Step 4: Debug EC2 Host
      - name: Debug Host
        run: echo "Host is ${{ secrets.EC2_HOST }}"

      # Step 5: Deploy to EC2 over SSH
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          debug: true
          script: |
            # Login to private Docker registry
            sudo docker login invest.virtualintelligence.co.in -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}

            # Stop and remove old container if it exists
            sudo docker stop frontend-con || true
            sudo docker rm frontend-con || true

            # Pull the latest image with commit SHA
            sudo docker pull invest.virtualintelligence.co.in/bma/frontend:${{ github.sha }}

            # Run the new container
            sudo docker run -d --name frontend-con -p 3000:3000 invest.virtualintelligence.co.in/bma/frontend:${{ github.sha }}

            # Wait and check logs
            sleep 5
            sudo docker logs frontend-con
