name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # ya 'master' ya jo bhi teri default branch hai

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/deepuprajapati/deepak-frontend:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/deepuprajapati/deepak-frontend:latest
