name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Apni default branch ka naam yaha daal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u deepuprajapati --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/deepuprajapati/deepak-frontend:latest .
        docker push ghcr.io/deepuprajapati/deepak-frontend:latest
