name: Deploy React App to EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.prajapatideepu003@gmail.com }}
        password: ${{ secrets.dockerhub }}

    - name: Build & Push Docker image
      run: |
        docker build -t Deepuprajpat/backnd:latest .
        docker push Deepuprajapat/backnd:latest

    - name: Debug Host
      run: echo "Host is ${{ secrets.54.146.240.40 }}" #To check if the secret is set correctly

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.54.146.240.40 }}
        username: ${{ secrets.ubuntu }}
        key: ${{ secrets.-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCFo8EW/vlSr4e5p3JX2ySG+0M/TX2XO0NgdtfpOeoorgAAAKDCXnLmwl5y
5gAAAAtzc2gtZWQyNTUxOQAAACCFo8EW/vlSr4e5p3JX2ySG+0M/TX2XO0NgdtfpOeoorg
AAAEBO+kE5QpcQS9bYCVdf98++ks8Rjr17pQo/gNBE5bRDx4WjwRb++VKvh7mnclfbJIb7
Qz9NfZc7Q2B21+k56iiuAAAAFnVidW50dUBpcC0xNzItMzEtODQtOTYBAgMEBQYH
-----END OPENSSH PRIVATE KEY----- }}
        script: |
          docker login -u ${{ secrets.prajapatideepu003@gmail.com }} -p ${{ secrets.dockerhub }}
          docker pull Deepuprajapat/backnd:latest
          docker stop backnd || true
          docker rm backnd || true
          docker run -d --name bma -p 3000:80 Deepuprajapat/backnd:latest
