name: Build and Push Docker Images

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up commit hash and lowercase repo
        id: vars
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker Images
        run: |
          docker build -t ghcr.io/${{ env.REPO_LOWER }}:${{ env.SHORT_SHA }} .

      - name: List all docker images
        run: docker images

      - name: Push Docker Images
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ env.REPO_LOWER }}:${{ env.SHORT_SHA }}

      - name: Send Slack Notification
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"✅ Docker Image Successfully Built & Pushed for *${{ github.repository }}* on branch *main* (commit: ${{ env.SHORT_SHA }})\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
