name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u Deepuprajapati --password-stdin

      - name: Build Docker image
        run: docker build -f Dockerfile -t ghcr.io/Deepuprajapati/deepak-frontend:latest .

      - name: Push Docker image
        run: docker push ghcr.io/Deepuprajapati/deepak-frontend:latest
